# Numpy 

In [2]:
import numpy as np

# Criar 

In [5]:
data = np.random.rand(2, 3, 4)
zeros = np.zeros((2, 2, 2))
full = np.full((2, 2, 2), 7)
ones = np.ones((2, 2, 2))

In [6]:
data

array([[[0.42613687, 0.18967571, 0.00663199, 0.55849048],
        [0.42105195, 0.79018632, 0.17617185, 0.01315724],
        [0.42521018, 0.51859021, 0.74307119, 0.94445752]],

       [[0.24177626, 0.08114132, 0.53312625, 0.60089846],
        [0.77696617, 0.36675929, 0.24819329, 0.14602575],
        [0.38551041, 0.58244683, 0.62412351, 0.08434029]]])

In [10]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [11]:
arr = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

In [13]:
type(arr)

numpy.ndarray

# Ler

In [14]:
# Attribute
shape = data.shape
size = data.size
types = data.dtype

In [17]:
type

type

In [37]:
# Slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singleval = data[1][0][1]

In [39]:
singleval

0.08114132118389783

In [28]:
data

array([[[0.42613687, 0.18967571, 0.00663199, 0.55849048],
        [0.42105195, 0.79018632, 0.17617185, 0.01315724],
        [0.42521018, 0.51859021, 0.74307119, 0.94445752]],

       [[0.24177626, 0.08114132, 0.53312625, 0.60089846],
        [0.77696617, 0.36675929, 0.24819329, 0.14602575],
        [0.38551041, 0.58244683, 0.62412351, 0.08434029]]])

# Atualizar 

In [41]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [42]:
list1

array([0.91802485, 0.1145303 , 0.18049762, 0.43132453, 0.17014724,
       0.58933735, 0.09792924, 0.74619191, 0.5699463 , 0.1424888 ])

In [44]:
# Base de criação 
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [48]:
dot

2.035755378478524

In [49]:
# Funções iniciais 
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2, 7)
log = np.log(25)
exp = ([2, 3])
mins = np.min(list1)
maxs = np.max(list1)

In [59]:
maxs

0.9180248501621866

In [60]:
data

array([[[0.42613687, 0.18967571, 0.00663199, 0.55849048],
        [0.42105195, 0.79018632, 0.17617185, 0.01315724],
        [0.42521018, 0.51859021, 0.74307119, 0.94445752]],

       [[0.24177626, 0.08114132, 0.53312625, 0.60089846],
        [0.77696617, 0.36675929, 0.24819329, 0.14602575],
        [0.38551041, 0.58244683, 0.62412351, 0.08434029]]])

In [61]:
data[0][0][0] = 700

In [62]:
data

array([[[7.00000000e+02, 1.89675711e-01, 6.63198651e-03, 5.58490478e-01],
        [4.21051946e-01, 7.90186324e-01, 1.76171848e-01, 1.31572363e-02],
        [4.25210181e-01, 5.18590214e-01, 7.43071191e-01, 9.44457517e-01]],

       [[2.41776256e-01, 8.11413212e-02, 5.33126252e-01, 6.00898455e-01],
        [7.76966168e-01, 3.66759289e-01, 2.48193294e-01, 1.46025754e-01],
        [3.85510409e-01, 5.82446833e-01, 6.24123515e-01, 8.43402938e-02]]])

In [63]:
data.sort()
data

array([[[6.63198651e-03, 1.89675711e-01, 5.58490478e-01, 7.00000000e+02],
        [1.31572363e-02, 1.76171848e-01, 4.21051946e-01, 7.90186324e-01],
        [4.25210181e-01, 5.18590214e-01, 7.43071191e-01, 9.44457517e-01]],

       [[8.11413212e-02, 2.41776256e-01, 5.33126252e-01, 6.00898455e-01],
        [1.46025754e-01, 2.48193294e-01, 3.66759289e-01, 7.76966168e-01],
        [8.43402938e-02, 3.85510409e-01, 5.82446833e-01, 6.24123515e-01]]])

In [64]:
print(data.shape)

(2, 3, 4)


In [65]:
data = data.reshape((2, 2, -1))
data.shape

(2, 2, 6)

In [67]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3, 4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [68]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# Deletar

In [69]:
data

array([[[6.63198651e-03, 1.89675711e-01, 5.58490478e-01, 7.00000000e+02,
         1.31572363e-02, 1.76171848e-01],
        [4.21051946e-01, 7.90186324e-01, 4.25210181e-01, 5.18590214e-01,
         7.43071191e-01, 9.44457517e-01]],

       [[8.11413212e-02, 2.41776256e-01, 5.33126252e-01, 6.00898455e-01,
         1.46025754e-01, 2.48193294e-01],
        [3.66759289e-01, 7.76966168e-01, 8.43402938e-02, 3.85510409e-01,
         5.82446833e-01, 6.24123515e-01]]])

In [72]:
np.delete(data, 0, axis=1)

array([[[0.42105195, 0.79018632, 0.42521018, 0.51859021, 0.74307119,
         0.94445752]],

       [[0.36675929, 0.77696617, 0.08434029, 0.38551041, 0.58244683,
         0.62412351]]])

In [75]:
np.save("new array", data) # Salvando array

In [80]:
test = np.load("new array.npy")

In [81]:
test

array([[[6.63198651e-03, 1.89675711e-01, 5.58490478e-01, 7.00000000e+02,
         1.31572363e-02, 1.76171848e-01],
        [4.21051946e-01, 7.90186324e-01, 4.25210181e-01, 5.18590214e-01,
         7.43071191e-01, 9.44457517e-01]],

       [[8.11413212e-02, 2.41776256e-01, 5.33126252e-01, 6.00898455e-01,
         1.46025754e-01, 2.48193294e-01],
        [3.66759289e-01, 7.76966168e-01, 8.43402938e-02, 3.85510409e-01,
         5.82446833e-01, 6.24123515e-01]]])

In [105]:
# Criando novo array
numbers = np.array([2, 4, 5, 2, 9, 1, 3, 1, 6, 1], np.int16)

print(numbers[-1])
print(numbers.dtype)

1
int16


In [106]:
numbers[3] = 7
print(numbers)

[2 4 5 7 9 1 3 1 6 1]


In [107]:
# array bidimiensional

bid = np.array([[1, 3, 5], [6, 3, 1], [3, 5, 7]])
print(bid)

[[1 3 5]
 [6 3 1]
 [3 5 7]]


In [108]:
print(bid[1, 2])

1


In [109]:
bid[0, 1] = 8
print(bid[0, 1])

8


In [110]:
print(bid)

[[1 8 5]
 [6 3 1]
 [3 5 7]]


In [111]:
# Visualizar coluna inteira
print('Primeira Coluna: ', bid[:,0])
print('Segunda Coluna: ', bid[:,1])
print('Terceira Coluna: ', bid[:,2])

Primeira Coluna:  [1 6 3]
Segunda Coluna:  [8 3 5]
Terceira Coluna:  [5 1 7]


In [112]:
# Visualizar linha inteira 
print('Primeira Linha: ', bid[0,:])
print('Segunda Linha: ', bid[1,:])
print('Terceira Linha: ', bid[2,:])

Primeira Linha:  [1 8 5]
Segunda Linha:  [6 3 1]
Terceira Linha:  [3 5 7]


In [113]:
# Número de dimensões de um array:
print(numbers.ndim)
print(bid.ndim)

1
2


In [116]:
# Tamanho do array
print(numbers.shape)
print(bid.shape)

(10,)
(3, 3)


In [117]:
# Número de elementos de um array
print(numbers.size)
print(bid.size)

10
9


# Array 3D (Tridimensional) [Bloco][Linha][Coluna]

In [119]:
cubo = np.array([[[1, 4, 7], [3, 5, 2]], [[5, 6, 0], [7, 4, 1]], [[2, 8, 8], [0, 3, 6]]])
print('Array Tridimensional:\n ', cubo)

Array Tridimensional:
  [[[1 4 7]
  [3 5 2]]

 [[5 6 0]
  [7 4 1]]

 [[2 8 8]
  [0 3 6]]]


In [121]:
print('\nItem na posição 0,0,0: ', cubo[0,0,0])
print('Item na posição 1,0,0: ', cubo[1,0,0])
print('Item na posição 2,0,0: ', cubo[2,0,0])


Item na posição 0,0,0:  1
Item na posição 1,0,0:  5
Item na posição 2,0,0:  2


In [122]:
print('Número de dimensões do array cubo: ', cubo.ndim)

print('Tamanho do array cubo: ', cubo.shape)

print('Total de Elementos do array cubo: ', cubo.size)

Número de dimensões do array cubo:  3
Tamanho do array cubo:  (3, 2, 3)
Total de Elementos do array cubo:  18


In [123]:
tri = np.array([ [ [0,0,0],[1,1,1],[2,2,2] ],[ [4,4,4],[5,5,5],[6,6,6] ] ])
print(tri)

[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[4 4 4]
  [5 5 5]
  [6 6 6]]]


In [124]:
for i in range(2):
    for j in range(3):
       for k in range(3):
            print('Posição (0),(1),(2): (3)'.format(i,j,k,tri[i][j][k]))

Posição (0),(1),(2): (3)
Posição (0),(1),(2): (3)
Posição (0),(1),(2): (3)
Posição (0),(1),(2): (3)
Posição (0),(1),(2): (3)
Posição (0),(1),(2): (3)
Posição (0),(1),(2): (3)
Posição (0),(1),(2): (3)
Posição (0),(1),(2): (3)
Posição (0),(1),(2): (3)
Posição (0),(1),(2): (3)
Posição (0),(1),(2): (3)
Posição (0),(1),(2): (3)
Posição (0),(1),(2): (3)
Posição (0),(1),(2): (3)
Posição (0),(1),(2): (3)
Posição (0),(1),(2): (3)
Posição (0),(1),(2): (3)
